# Generated by Django 4.2 on 2024-10-25 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('provider', models.CharField(choices=[('yandex', 'Yandex'), ('gmail', 'Gmail'), ('mailru', 'Mail.ru')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('sent_date', models.DateTimeField()),
                ('received_date', models.DateTimeField()),
                ('body', models.TextField()),
                ('attachments', models.FileField(blank=True, null=True, upload_to='email_attachments/')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message.emailaccount')),
            ],
            options={
                'ordering': ('received_date',),
            },
        ),
    ]
